name: wanderwise_shared
description: Shared code, models, and services for WanderWise mobile and admin applications.

version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  # Firebase (Core services)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # Models and Data
  json_annotation: ^4.9.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 